version: "3.8"

services:

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    ports:
      - "5000:5000"
    volumes:
      - /mnt/configs/kavita/config:/kavita/config
      - /mnt/media/books/comics:/kavita/media
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/configs/calibre-web/config:/config
      - /mnt/media/books/books:/books
    ports:
      - "8083:8083"
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - "13378:80"
    volumes:
      - /mnt/media/configs/audiobookshelf/config:/config
      - /mnt/media/books/metaddata/audiobookshelf/metadata:/metadata
      - /mnt/media/books/audiobooks:/audiobooks
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/configs/nzbget/config:/config
      - /mnt/media/books/downloads:/downloads
    ports:
      - "6789:6789"
    restart: unless-stopped
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    ports:
      - "5299:5299"
    volumes:
      - /mnt/media/configs/lazylibrarian/config:/config
      - /mnt/media/books/books:/books
      - /mnt/media/books/audiobooks:/audiobooks
      - /mnt/media/books/metadata/lazylibrarian:/config
      - /mnt/media/books/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lazylibrarian.rule=Host(`read-get.lthome.com`)"
      - "traefik.http.routers.lazylibrarian.entrypoints=websecure"
      - "traefik.http.routers.lazylibrarian.tls.certresolver=letsencrypt"
      - "traefik.http.services.lazylibrarian.loadbalancer.server.port=5299"
    restart: unless-stopped
